FROM osixia/openldap:1.1.9

COPY security.ldif /container/service/slapd/assets/config/bootstrap/ldif/90-osiam-security.ldif
COPY test-data.ldif /container/service/slapd/assets/config/bootstrap/ldif/99-test-data.ldif
